export default {
  login: "PawelHamryszak",
  id: 105717616,
  node_id: "U_kgDOBk0fcA",
  avatar_url: "https://avatars.githubusercontent.com/u/105717616?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/PawelHamryszak",
  html_url: "https://github.com/PawelHamryszak",
  followers_url: "https://api.github.com/users/PawelHamryszak/followers",
  following_url:
    "https://api.github.com/users/PawelHamryszak/following{/other_user}",
  gists_url: "https://api.github.com/users/PawelHamryszak/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/PawelHamryszak/starred{/owner}{/repo}",
  subscriptions_url:
    "https://api.github.com/users/PawelHamryszak/subscriptions",
  organizations_url: "https://api.github.com/users/PawelHamryszak/orgs",
  repos_url: "https://api.github.com/users/PawelHamryszak/repos",
  events_url: "https://api.github.com/users/PawelHamryszak/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/PawelHamryszak/received_events",
  type: "User",
  site_admin: false,
  name: null,
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 32,
  public_gists: 0,
  followers: 1,
  following: 2,
  created_at: "2022-05-17T10:57:59Z",
  updated_at: "2023-06-11T23:05:59Z",
};
